os: Visual Studio 2017

configuration:
  #- Debug
  - Release

environment:
  matrix:
    - GENERATOR: "MinGW Makefiles"
      CXX_PATH: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GENERATOR: "Visual Studio 12 2013 Win64"
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 15 2017 Win64"
    - GENERATOR: "Visual Studio 15 2017"

matrix:
  fast_finish: true

install:
  - git submodule update --init
  - if "%GENERATOR%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
  - if not "%CXX_PATH%"=="" (set "PATH=%PATH%;%CXX_PATH%")

build_script:
  - cmake -H. -Bbuild -G"%GENERATOR%" -DEARCUT_WARNING_IS_ERROR=ON
  - cmake --build build --config %configuration%

test_script:
  - cd build
  - if exist %configuration% (cd "%configuration%") 
  - call "tests.exe"
  - call "bench.exe"